; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
build_cache_dir = .cache  ; 这会在项目根目录下创建一个 .cache 文件夹存放缓存
default_envs = esp32-s3-wifi-ota ; 默认编译串口版本，可在此切换为 esp32-s3-wifi

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600
upload_speed = 921600
lib_ldf_mode = chain+
board_microros_distro = humble
build_flags = 
    -DWIFI_SSID=\"CUMT_Stu_Fast\"
    -DWIFI_PASSWORD=\"s4b5071nb\"
    -DAGENT_IP=\"192.168.10.198\"
    -DAGENT_PORT=8888
lib_deps =
    https://gitee.com/ohhuo/micro_ros_platformio.git

[env:esp32-s3-serial]
extends = env
board_microros_transport = serial
build_flags = 
    ${env.build_flags}
    -DUSE_SERIAL_TRANSPORT

[env:esp32-s3-wifi]
extends = env
board_microros_transport = wifi
build_flags = 
    ${env.build_flags}
    -DUSE_WIFI_TRANSPORT

[env:esp32-s3-wifi-ota]
extends = env:esp32-s3-wifi
upload_protocol = espota
upload_port = 192.168.10.103

[env:esp32-s3-serial-ota]
extends = env:esp32-s3-serial
upload_protocol = espota
upload_port = 192.168.10.103
